Traceback (most recent call last):
  File "/home/project2/.local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 57, in <module>
    raise ImportError(_("The Jupyter Notebook requires tornado >= 5.0, but you have %s") % tornado.version)
ImportError: The Jupyter Notebook requires tornado >= 5.0, but you have 4.3
Traceback (most recent call last):
  File "/home/project2/.local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 57, in <module>
    raise ImportError(_("The Jupyter Notebook requires tornado >= 5.0, but you have %s") % tornado.version)
ImportError: The Jupyter Notebook requires tornado >= 5.0, but you have 4.3
Traceback (most recent call last):
  File "/home/project2/.local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 57, in <module>
    raise ImportError(_("The Jupyter Notebook requires tornado >= 5.0, but you have %s") % tornado.version)
ImportError: The Jupyter Notebook requires tornado >= 5.0, but you have 4.3
Traceback (most recent call last):
  File "/home/project2/.local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 57, in <module>
    raise ImportError(_("The Jupyter Notebook requires tornado >= 5.0, but you have %s") % tornado.version)
ImportError: The Jupyter Notebook requires tornado >= 5.0, but you have 4.3
Traceback (most recent call last):
  File "/home/project2/.local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 57, in <module>
    raise ImportError(_("The Jupyter Notebook requires tornado >= 5.0, but you have %s") % tornado.version)
ImportError: The Jupyter Notebook requires tornado >= 5.0, but you have 4.3
Traceback (most recent call last):
  File "/home/project2/.local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 57, in <module>
    raise ImportError(_("The Jupyter Notebook requires tornado >= 5.0, but you have %s") % tornado.version)
ImportError: The Jupyter Notebook requires tornado >= 5.0, but you have 4.3
Traceback (most recent call last):
  File "/home/project2/.local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 57, in <module>
    raise ImportError(_("The Jupyter Notebook requires tornado >= 5.0, but you have %s") % tornado.version)
ImportError: The Jupyter Notebook requires tornado >= 5.0, but you have 4.3
Traceback (most recent call last):
  File "/home/project2/.local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 57, in <module>
    raise ImportError(_("The Jupyter Notebook requires tornado >= 5.0, but you have %s") % tornado.version)
ImportError: The Jupyter Notebook requires tornado >= 5.0, but you have 4.3
Traceback (most recent call last):
  File "/home/project2/.local/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/notebookapp.py", line 57, in <module>
    raise ImportError(_("The Jupyter Notebook requires tornado >= 5.0, but you have %s") % tornado.version)
ImportError: The Jupyter Notebook requires tornado >= 5.0, but you have 4.3
[I 18:41:28.178 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.6.1
[I 18:41:28.181 NotebookApp] Serving notebooks from local directory: /home/project2/extras/temp/jupiter-explorations/SpeechToTextHack
[I 18:41:28.181 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 18:41:28.181 NotebookApp] http://14.139.184.220:8888/
[I 18:41:28.181 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 18:41:32.652 NotebookApp] 404 GET /api/contents/SpeechToTextHack?type=directory&_=1681562501374 (223.186.53.231): file or directory does not exist: 'SpeechToTextHack'
[W 18:41:32.652 NotebookApp] file or directory does not exist: 'SpeechToTextHack'
[W 18:41:32.653 NotebookApp] 404 GET /api/contents/SpeechToTextHack?type=directory&_=1681562501374 (223.186.53.231) 2.980000ms referer=http://ws.mec.ac.in:8888/tree/SpeechToTextHack
[I 18:41:37.411 NotebookApp] 302 GET / (223.186.53.231) 1.070000ms
[W 18:41:44.797 NotebookApp] 404 GET /static/components/marked/lib/marked.js?v=20230415184128 (223.186.53.231) 12.000000ms referer=http://ws.mec.ac.in:8888/tree?
[W 18:41:50.296 NotebookApp] Notebook Untitled.ipynb is not trusted
[I 18:41:50.982 NotebookApp] Kernel started: 9f9fa0ea-42d0-4688-bc79-bb48c5196315, name: python3
[I 18:43:52.618 NotebookApp] Saving file at /Untitled.ipynb
[I 18:44:44.357 NotebookApp] 302 GET / (223.186.53.231) 1.100000ms
[W 18:44:56.752 NotebookApp] 404 GET /static/components/marked/lib/marked.js?v=20230415184128 (223.186.53.231) 3.290000ms referer=http://ws.mec.ac.in:8888/tree?
[I 18:45:11.050 NotebookApp] Kernel interrupted: 9f9fa0ea-42d0-4688-bc79-bb48c5196315
[I 18:45:54.420 NotebookApp] Saving file at /Untitled.ipynb
/home/project2/.local/lib/python3.9/site-packages/nbformat/__init__.py:129: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate(nb)
/home/project2/.local/lib/python3.9/site-packages/notebook/services/contents/manager.py:353: MissingIDFieldWarning: Code cell is missing an id field, this will become a hard error in future nbformat versions. You may want to use `normalize()` on your notebooks before validations (available since nbformat 5.1.4). Previous versions of nbformat are fixing this issue transparently, and will stop doing so in the future.
  validate_nb(model['content'])
[E 18:46:52.740 NotebookApp] Uncaught exception in ZMQStream callback
    Traceback (most recent call last):
      File "/home/project2/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/project2/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/project2/.local/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/project2/.local/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/iostream.py", line 540, in write
        self._write_buffer.append(data)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/iostream.py", line 157, in append
        b += data  # type: ignore
    BufferError: Existing exports of data: object cannot be re-sized
[E 18:46:52.753 NotebookApp] Uncaught exception in zmqstream callback
    Traceback (most recent call last):
      File "/home/project2/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
        self._handle_recv()
      File "/home/project2/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
        self._run_callback(callback, msg)
      File "/home/project2/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
        f = callback(*args, **kwargs)
      File "/home/project2/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
        return callback(self, msg)
      File "/home/project2/.local/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
        super()._on_zmq_reply(stream, msg)
      File "/home/project2/.local/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
        self.write_message(msg, binary=isinstance(msg, bytes))
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
        return self.ws_connection.write_message(message, binary=binary)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
        fut = self._write_frame(True, opcode, message, flags=flags)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/iostream.py", line 540, in write
        self._write_buffer.append(data)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/iostream.py", line 157, in append
        b += data  # type: ignore
    BufferError: Existing exports of data: object cannot be re-sized
Exception in callback BaseAsyncIOLoop._handle_events(32, 1)
handle: <Handle BaseAsyncIOLoop._handle_events(32, 1)>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/project2/.local/lib/python3.9/site-packages/tornado/platform/asyncio.py", line 206, in _handle_events
    handler_func(fileobj, events)
  File "/home/project2/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 621, in _handle_events
    self._handle_recv()
  File "/home/project2/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 650, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/project2/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 584, in _run_callback
    f = callback(*args, **kwargs)
  File "/home/project2/.local/lib/python3.9/site-packages/zmq/eventloop/zmqstream.py", line 308, in stream_callback
    return callback(self, msg)
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 572, in _on_zmq_reply
    super()._on_zmq_reply(stream, msg)
  File "/home/project2/.local/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 256, in _on_zmq_reply
    self.write_message(msg, binary=isinstance(msg, bytes))
  File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 339, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
    return self.stream.write(frame)
  File "/home/project2/.local/lib/python3.9/site-packages/tornado/iostream.py", line 540, in write
    self._write_buffer.append(data)
  File "/home/project2/.local/lib/python3.9/site-packages/tornado/iostream.py", line 157, in append
    b += data  # type: ignore
BufferError: Existing exports of data: object cannot be re-sized
[I 18:47:52.803 NotebookApp] Saving file at /Untitled.ipynb
[I 18:49:32.176 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:ca087cb5b62846c8b94523d0eab70382
[I 18:49:34.844 NotebookApp] Kernel restarted: 9f9fa0ea-42d0-4688-bc79-bb48c5196315
[I 18:49:35.365 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:ca087cb5b62846c8b94523d0eab70382
[I 18:49:35.545 NotebookApp] Replaying 400 buffered messages
[I 18:49:51.521 NotebookApp] Saving file at /Untitled.ipynb
[I 18:51:54.586 NotebookApp] Saving file at /Untitled.ipynb
[I 18:53:51.413 NotebookApp] Saving file at /Untitled.ipynb
[I 18:59:51.538 NotebookApp] Saving file at /Untitled.ipynb
[I 19:00:59.115 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:ca087cb5b62846c8b94523d0eab70382
[I 19:01:01.779 NotebookApp] Kernel restarted: 9f9fa0ea-42d0-4688-bc79-bb48c5196315
[I 19:01:02.594 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:ca087cb5b62846c8b94523d0eab70382
[I 19:01:02.798 NotebookApp] Replaying 6 buffered messages
[I 19:01:51.555 NotebookApp] Saving file at /Untitled.ipynb
[I 19:02:39.461 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:ca087cb5b62846c8b94523d0eab70382
[I 19:02:39.736 NotebookApp] Kernel restarted: 9f9fa0ea-42d0-4688-bc79-bb48c5196315
[I 19:02:40.345 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:ca087cb5b62846c8b94523d0eab70382
[I 19:02:40.351 NotebookApp] Replaying 3 buffered messages
[I 19:03:55.939 NotebookApp] Saving file at /Untitled.ipynb
[I 19:05:54.803 NotebookApp] Saving file at /Untitled.ipynb
[I 19:07:53.123 NotebookApp] Saving file at /Untitled.ipynb
[W 19:09:40.376 NotebookApp] WebSocket ping timeout after 117589 ms.
[I 19:09:45.383 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:ca087cb5b62846c8b94523d0eab70382
[I 19:18:22.049 NotebookApp] Saving file at /Untitled.ipynb
[I 20:41:48.877 NotebookApp] Saving file at /Untitled.ipynb
[W 20:41:50.276 NotebookApp] Notebook Untitled.ipynb is not trusted
[I 20:43:52.638 NotebookApp] Saving file at /Untitled.ipynb
[I 21:03:22.559 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:03:25.522 NotebookApp] Kernel restarted: 9f9fa0ea-42d0-4688-bc79-bb48c5196315
[I 21:03:27.265 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:03:27.768 NotebookApp] Replaying 6 buffered messages
[I 21:03:51.654 NotebookApp] Saving file at /Untitled.ipynb
[I 21:05:55.176 NotebookApp] Saving file at /Untitled.ipynb
[I 21:13:54.911 NotebookApp] Saving file at /Untitled.ipynb
[I 21:15:56.585 NotebookApp] Saving file at /Untitled.ipynb
[I 21:17:56.292 NotebookApp] Saving file at /Untitled.ipynb
[I 21:19:59.569 NotebookApp] Saving file at /Untitled.ipynb
[W 21:23:57.296 NotebookApp] WebSocket ping timeout after 101189 ms.
[I 21:24:02.301 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:24:49.868 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:24:50.279 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[W 21:24:50.280 NotebookApp] zmq message arrived on closed channel
[I 21:25:54.268 NotebookApp] Saving file at /Untitled.ipynb
[I 21:25:59.248 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:25:59.753 NotebookApp] Replaying 2 buffered messages
[I 21:26:10.124 NotebookApp] Saving file at /Untitled.ipynb
[W 21:26:10.256 NotebookApp] Replacing stale connection: 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:10.367 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:10.369 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:10.524 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[W 21:26:10.526 NotebookApp] zmq message arrived on closed channel
[I 21:26:11.914 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:12.073 NotebookApp] Replaying 2 buffered messages
[W 21:26:18.687 NotebookApp] Replacing stale connection: 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:18.820 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:18.822 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:19.054 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:20.065 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:20.260 NotebookApp] Replaying 3 buffered messages
[W 21:26:50.213 NotebookApp] Replacing stale connection: 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:52.758 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:52.760 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[W 21:26:52.894 NotebookApp] Replacing stale connection: 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[E 21:26:52.931 NotebookApp] Uncaught exception GET /api/kernels/9f9fa0ea-42d0-4688-bc79-bb48c5196315/channels?session_id=33679305888d48c28df7f9ae39c0ec46 (223.186.53.231)
    HTTPServerRequest(protocol='http', host='ws.mec.ac.in:8888', method='GET', uri='/api/kernels/9f9fa0ea-42d0-4688-bc79-bb48c5196315/channels?session_id=33679305888d48c28df7f9ae39c0ec46', version='HTTP/1.1', remote_ip='223.186.53.231')
    Traceback (most recent call last):
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/project2/.local/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 377, in get
        yield super().get(kernel_id=kernel_id)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/project2/.local/lib/python3.9/site-packages/notebook/base/zmqhandlers.py", line 293, in get
        yield maybe_future(res)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/gen.py", line 776, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/home/project2/.local/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 355, in pre_get
        yield self._register_session()
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/gen.py", line 769, in run
        value = future.result()
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/gen.py", line 234, in wrapper
        yielded = ctx_run(next, result)
      File "/home/project2/.local/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 391, in _register_session
        yield stale_handler.close()
      File "/home/project2/.local/lib/python3.9/site-packages/notebook/services/kernels/handlers.py", line 575, in close
        super().close()
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 485, in close
        self.ws_connection.close(code, reason)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 1263, in close
        self._write_frame(True, 0x8, close_data)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
        return self.stream.write(frame)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/iostream.py", line 540, in write
        self._write_buffer.append(data)
      File "/home/project2/.local/lib/python3.9/site-packages/tornado/iostream.py", line 157, in append
        b += data  # type: ignore
    BufferError: Existing exports of data: object cannot be re-sized
[E 21:26:52.948 NotebookApp] {
      "Host": "ws.mec.ac.in:8888",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"
    }
[E 21:26:52.948 NotebookApp] 500 GET /api/kernels/9f9fa0ea-42d0-4688-bc79-bb48c5196315/channels?session_id=33679305888d48c28df7f9ae39c0ec46 (223.186.53.231) 55.700000ms referer=None
[I 21:26:52.949 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:26:56.890 NotebookApp] Restoring connection for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[W 21:29:26.920 NotebookApp] WebSocket ping timeout after 119664 ms.
[I 21:29:31.927 NotebookApp] Starting buffering for 9f9fa0ea-42d0-4688-bc79-bb48c5196315:33679305888d48c28df7f9ae39c0ec46
[I 21:52:54.861 NotebookApp] 302 GET / (64.226.82.186) 35.740000ms
[I 23:59:54.160 NotebookApp] 302 GET / (3.92.166.170) 0.870000ms
[I 23:59:54.420 NotebookApp] 302 GET /tree (3.92.166.170) 2.150000ms
[I 02:54:20.982 NotebookApp] 302 GET / (223.186.53.243) 10.880000ms
[W 02:54:22.849 NotebookApp] 404 GET /static/components/marked/lib/marked.js?v=20230415184128 (223.186.53.243) 3.190000ms referer=http://ws.mec.ac.in:8888/tree?
[I 10:10:41.943 NotebookApp] 302 GET / (192.241.215.17) 35.850000ms
